spring.application.name=keiba-app

spring.datasource.url=jdbc:postgresql://localhost:5432/keibadb
spring.datasource.username=keiba
spring.datasource.password=keiba

spring.jpa.hibernate.ddl-auto=update

discord.webhook.url=${DISCORD_WEBHOOK_URL:}